management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

broker:
  service:
    id: "dababase-custom"
    name: "Custom Database"
    url: "jdbc:postgresql://mydbhost/db?user=foo&password=secret"
    description: "Expose a custom database as a service"
    icon: "https://i.imgur.com/WIE9ayD.png"
    provider: "Pivotal Software Inc."
  credentials:
    password: "admin"
